version: '2'
services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - "./mysql/data:/var/lib/mysql"
    ports:
      - "3306:3306"
  
  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin/phpmyadmin
    environment:
      # - PMA_ARBITRARY=1
      # - PMA_HOST=mysql
      #- PMA_USER=docker
      #- PMA_PASSWORD=root
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: pass
      PMA_HOST: db

    ports:
      - "8080:80"
    volumes:
      - "./phpmyadmin/session:/session"
      - "./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php"
    links:
      - mysql
      
  python:
    image: python


  php:
    build: ./php
    ports:
      - '80:80'
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql

  datascience-notebook:
     container_name: "datascience-notebook"
     image: jupyter/datascience-notebook
     ports:
       - '8888:8888'
     volumes:
       - './datascience-notebook:/home/jovyan/work'
     command: start-notebook.sh --NotebookApp.token=''


     #volumes:
     # db:
